App({
  globalData: {
    bleConnection: {
      connected: false,
      deviceName: '',
      deviceId: '',
      serviceId: '',
      notifyCharId: '',
      writeCharId: '',
      writeType: 'write',
    },
    fanDashboard: {
      connected: false,
      deviceName: '未连接风扇',
      fanOn: false,
      speedLevel: 1,
      speed: '--',
      temperature: '--',
      humidity: '--',
      currentMode: 'normal',
      currentModeLabel: '普通模式',
      smartMode: false,
      timerDisplay: '未设置',
      timerTargetText: '',
      currentSceneName: '',
    },
    fanPageState: {
      fanOn: false,
      currentMode: 'normal',
      speedLevel: 1,
      fanSpeedClass: 'fan-off',
      fanStatusText: '停止',
      currentSceneKey: '',
      currentSceneName: '',
      smartMode: false,
      lastAutoLevel: 0,
      countdownMinutes: '30',
      closeAtTime: '22:00',
      timerActive: false,
      timerType: '',
      timerDisplay: '未设置',
      timerTargetText: '',
      timerTargetTimestamp: 0,
      temperature: '--',
      humidity: '--',
      speed: '--',
      telemetryText: '等待 STM32 回传数据',
      logs: [],
    },
    debugPageState: {
      receivedData: [],
      sendText: '',
      sendMode: 'text',
      canSend: false,
      hexDisplay: false,
      scrollToId: '',
    },
  },

  onLaunch() {
    console.log('BLE调试助手启动');
  },
});
